# Rcpp

[Rcpp](http://www.rcpp.org/)

[Rcpp4everyone](https://teuder.github.io/rcpp4everyone_en/)

<https://dirk.eddelbuettel.com/papers/useR2019_rcpp_tutorial.pdf>

<https://www.runoob.com/cplusplus/cpp-tutorial.html>

## 数据结构

### 向量类

`NumericVector` `IntegerVector` `CharacterVector` `LogicalVector`

```{r}
library(Rcpp)
sourceCpp("function/sum_cpp.cpp")

sum_cpp(mpg$displ)
sum(mpg$displ)

sourceCpp("function/mean_cpp.cpp")
mean_cpp(mpg$displ)
```

`NumericMatrix` `IntegerMatrix` `CharacterMatrix` `LogicalMatrix`

### 数据框类

DataFrame

### 列表类

List

```{r}
# 平均百分比误差
sourceCpp("function/mpe.cpp")
mod <- lm(mpg ~ wt, data = mtcars)
mpe(mod)
```

### 函数类

```{r}
cppFunction("RObject callWithOne(Function f) {
  return f(1);
}")

callWithOne(function(x) x + 1)
callWithOne(paste)
```

### 属性

```{r}
cppFunction('NumericVector attribs() {
  NumericVector out = NumericVector::create(1, 2, 3);

  out.names() = CharacterVector::create("a", "b", "c");
  out.attr("my-attr") = "my-value";
  out.attr("class") = "my-class";

  return out;
}')


attribs()
```

## Rcpp sugar
