project:
  type: book
  output-dir: docs

book: 
  title: "大数据"
  reader-mode: true
  chapters:
    - index.qmd
    - data.table.qmd
    - arrow.qmd
    - Rcpp.qmd
    - parallel_computing.qmd
    - spark.qmd
    - Python_to_R.qmd
    - polars.qmd




execute:
  message: false 
  warning: false 

toc: true
toc-depth: 4
number-sections: true
number-depth: 4

code-fold: show
code-tools: true
code-link: true
code-summary: "Show the code"
knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

