# Polars

## [polars](https://docs.pola.rs/)

-   [R polars](https://pola-rs.github.io/r-polars/)

-   [Cookbook Polars for R](https://ddotta.github.io/cookbook-rpolars/)

```{r}
if(!require(polars))
    install.packages("polars", repos = "https://rpolars.r-universe.dev")

polars_info()
polars_code_completion_activate()
```

Polars 的主要函数存储在 “pl” 命名空间中，可以使用 “`pl$`” 前缀进行访问，以防止与其他组件和base R 函数名称冲突

```{r}
iris_polars <- pl$DataFrame(iris)
iris_polars
```

访问属性

```{r}
iris_polars$shape
iris_polars$height
iris_polars$width

# polars syntax
pl$DataFrame(iris)$
  select(c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"))$
  with_columns(
    pl$when(
      (pl$col("Petal.Length") / pl$col("Petal.Width") > 3)
    )$then(pl$lit("long"))$
      otherwise(pl$lit("large"))$
      alias("petal_type")
  )$
  filter(pl$col("Sepal.Length")$is_between(4.5, 5.5))$
  head(6)
```

```{r}
pl$read_csv("data/Advertising.csv")
```

## [tidypolars](https://tidypolars.etiennebacher.com/)

```{r}
if(!require(tidypolars))
    install.packages('tidypolars',
                     repos = c('https://etiennebacher.r-universe.dev', getOption("repos"))
    )

iris |> 
  as_polars_df() |> 
  select(starts_with(c("Sep", "Pet"))) |> 
  mutate(
    petal_type = ifelse((Petal.Length / Petal.Width) > 3, "long", "large")
  ) |> 
  filter(between(Sepal.Length, 4.5, 5.5)) |> 
  head()
```
